name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Optional)
        run: npm test

      - name: Deploy to Staging
        run: echo "Deployed to Staging Environment!"
